alphagov/govuk-e2e-tests

- tests/cdn.spec.js
This removes hardcoded urls for production environment from tests to do with redirecting apex and https upgrades.
> Enable tld redirect tests for staging and integration

- tests/cdn.spec.js
- tests/chat.spec.js
GOV.UK Chat is not yet available in production and service.gov.uk redirects aren't configured in staging and integration.
> Make tests run only in suitable environments

- tests/finder-frontend.spec.js
This tests for a (broken and mangled) ARIA region that no longer exists in our upcoming new UI for site search.
Instead, we should be looking for a stable long-lived link that has the added benefit of also verifying results are coming back.
> Finder Frontend: Update site search test

- .github/workflows/ci.yml
Adding security scans as per https://docs.publishing.service.gov.uk/manual/github.html#create-and-configure-a-new-gov-uk-repo
> Add security scans to CI

- tests/publisher.spec.js
This test was ported across from Smokey, but commented-out. We (the
Mainstream Publishing Experience team) would like this test reinstated
as it protects against issues when upgrading the Mongo driver that
aren't picked up otherwise.
It does modify state (by creating, and then deleting a Guide), which is
why it is tagged not to run in production.
> Reapply Mainstream Publisher test from Smokey

- tests/frontend.spec.js
- We want to make sure that when these apps are deployed frontend can still access them.
> Add backend app tags to relevant frontend tests

- tests/frontend.spec.js
- tests/government-frontend.spec.js
- government-frontend doesn't use search api as of https://github.com/alphagov/government-frontend/pull/3419
- frontend uses it now, but also we've removed the schema-name identifiers from main, so we have to update the locator.
> Move search-api test

- tests/chat.spec.js
Trello: https://trello.com/c/evNZhxxc/2285-set-up-410-page-for-govuk-chat-to-be-served-by-govuk
GOV.UK Chat is no longer hosted on [www.gov.uk](http://www.gov.uk/) and is available, behind
signon, on chat.publishing.service.gov.uk.
> Test chat against publishing host name

- tests/content-data.spec.js
- tests/whitehall.spec.js
Trello: https://trello.com/c/H4gmTEtf/3489-explore-adding-full-e2e-publishing-test
We currently lack any automated test that gives us confidence that publishing is working end to end, i.e. that an update from a publishing app becomes visible on the frontend. Adding such a test was highlighted as a recent [incident action](https://docs.google.com/document/d/14Hi5AkI6nf0l7Ot6KhjHu53Yq81F2vuRjjyMFtJWLcc/edit).
This commit adds a test that:
- Visits an existing 'test' document in Whitehall (available in all environments)
- Saves an edit to its draft content
- Verifies that the updated content is visible on the draft preview of that content
This tests the 'save draft' aspects of the publishing platform, which is a reasonably thorough verification that the connection from publishing app, to …
> Add full e2e test from publishing to frontend

- tests/government-frontend.spec.js
The text on this page has been updated. This commit updates the test to reflect the new text.
https://github.com/alphagov/frontend/pull/4681/files#diff-44438ce218f5287c58d0017f965d888715635d94280669896f75841fbd7b4cd7
> Update expected text on get involved page

- tests/frontend.spec.js
- tests/government-frontend.spec.js
The consolidation work has moved some routes to Frontend that the E2E test for government-frontend was using, so they would still pass even if government-frontend had fallen over. Update both test suites to reflect current situation.
> Update government frontend frontend tests

- tests/places-manager.spec.js
It doesn't seem that places-manager and publishing-api have ever depended on one another, the tag was added to the old smoketests by mistake (https://github.com/alphagov/smokey/commit/62135b65516ea9847ada6f236bac2417fe2c0e35)
> Remove publishing-api tag from places-manager-spec

- tests/frontend.spec.js
- tests/government-frontend.spec.js
Update service manual homepage tests to move them from `government-frontend` to `frontend`.
`government-frontend` isn't rendering /service-manual as of https://github.com/alphagov/government-frontend/pull/3628
Trello card: https://trello.com/c/ANPt33UZ/508-move-route-service-manual-homepage-only-from-government-frontend-to-frontend
> Move service manual homepage test

- tests/publisher.spec.js
[Trello](https://trello.com/c/xFZ5Fx1D/1657-looks-into-deploy-failures-for-publishing-api)
We're seeing a lot of failed Argo workflow runs in Publishing API each day, and a large proportion are because of the Publisher end-to-end test failing. We've noticed that multiple runs fail at almost the same time
We've found/note that:
- multiple runs fail with no more than a few minutes before and/or after each other throughout the day
- deleting the artefact created by the Smokey user in Publisher and then re-running the workflow can make the test pass
- the title of the artefact created in the test is not unique between runs
- the failed runs typically start appearing around 09:30/10:00 each morning, which we believe corresponds with an increase in Dependabot activity
Our theory then is that …
> Fix flaky Publisher test

- tests/publisher.spec.js
[Trello](https://trello.com/c/xFZ5Fx1D/1657-look-into-deploy-failures-for-publishing-api)
We attempted to fix some flakiness in 4ed3493138369fabf2a8987d9f705605409e5c42 but introduced a couple of mistakes. We're slightly surprised by the missing import not being picked up by the linter, but not the `replace`/`replaceAll` mistake. The end-to-end tests don't run in CI, so this wasn't spotted until it was deployed. We've run this locally using the Smokey user in integration to confirm it now works
> Fix Publisher end-to-end test

- tests/finder-frontend.spec.js
- Adds a `waitForURL` to one of the `finder-frontend` tests
- The test is failing on deployment to `production`
- We're not entirely sure why it's failing, but when testing locally it looks like after clicking the "search" button in the test, the test might continue its checks before the page has fully loaded.
> Add wait for correct URL in search test

- tests/finder-frontend.spec.js
- A test for `finder-frontend` search was looking for the `Sign in to your Universal Credit account` link when you search for "Universal Credit"
- However, Google can sometimes change the ranking of search results on `staging`/`integration` to demonstrate new features. This can make this test fail as the `Sign in to your Universal Credit account` link can disappear from page 1 of the results.
- Therefore we should use a search result that is a lot more likely to exist on Page 1 when searching for "Universal Credit"
- This commit changes the test to look for the `/universal-credit` landing page instead, which is a lot more likely to always exist when searching for "Universal Credit".
- It also makes the test specifically look for the link within the search results. This prevents this test …
> Change site search result test

- tests/licensing.spec.js
CodeQL alerted: This regular expression has an unescaped '.' before 'worldpay.com', so it might match more hosts than expected. Escape the dot (.) so it matches a literal dot, not any character. It was used in a test so was not going to exploited"
https://github.com/alphagov/govuk-e2e-tests/security/code-scanning/1
> Remediate Incomplete regular expression for hostnames

- tests/publisher.spec.js
Ensure that e2e tests will run successfully if the flipflop toggle for the new design system version of the publications page is enabled/disabled. The legacy check will be removed after enabling the toggle on by default
> Add check for class on new design system component for publications page

- tests/publisher.spec.js
The toggle for the design system on the publications page needs to re-enabled by default. The tests need to support checking on/off so that no e2e tests fail during the release process
> Add check for both progression and regression for design system toggle on publications page

- tests/publisher.spec.js
Previously we were checking for the existence of the text "publisher" without considering where that text was. As a result when we added a banner, the test would get confused and return multiple instances in a way not supported by the previous check.
Check has been updated to look within the specific header class.
Based on https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text
> Update Publisher e2e to be specific with its page text search

- tests/publisher.spec.js
Previous attempt at heading did not cover all bases, so trying it with a link target instead.
> Update publisher e2e to look for correct element

- tests/government-frontend.spec.js
- current target for this test points to a page which is now moved to frontend, so update to point to a page which is still on government-frontend.
https://trello.com/c/utYFvGDW/781-move-publication-from-government-frontend-to-frontend
> feat: change target of email test

- tests/finder-frontend.spec.js
The specific results returned from a search request are determined by Google Vertex. Sometimes there are problems with their algorithms so the results returned are not the ones that we expect. This causes the tests to fail and blocks deployment.
We have other, more details evaluations that run to check the quality of search results, so we don't need to rely on the e2e test for that, instead we should check things we can control, such as the user journey (homepage to search page) being as expected.
> Remove link check from search test

- tests/finder-frontend.spec.js
Follows on from: https://github.com/alphagov/govuk-e2e-tests/pull/276
Prepend the search query to the expected page title in the site search test.
The expectation for the test was checking the viewable text in the H1 rather than the content in the title tag in the head element which contains the full search query entered by the user.
> Update expected title in site search test

- tests/publisher.spec.js
- While we put the app in maintenance mode to test the migration to postgres
> Prevent e-2-e tests from running for Publisher in Integration

- tests/publisher.spec.js
The Publisher to postgres migration on Production will be taking place today so we will need this PR in place and ready for when we put the app in maintenance mode later today.
> Disable e2e tests in production for the final migration of publisher to postgres

- tests/feedback.spec.js
Introduced in https://github.com/alphagov/govuk-e2e-tests/pull/259, but browsers render things slightly differently, and we can't predict how the e2e test operating system is rendering the footer so the tests are failing.
> Delete footer test

- tests/collections.spec.js
Remove the check for the "Cabinet ministers" heading from the "ministers" page test for the collections app.
This heading does not exist when the ministers page is updated, this causes the e2e test to fail and block deployments.
Checking for the presence of the "Ministers" heading should be enough and is [consistent with other page tests](https://github.com/alphagov/govuk-e2e-tests/blob/main/tests/collections.spec.js#L88-L91) for `collections`.
> Update `collections` app test

- tests/chat.spec.js
Disable e2e tests in staging for chat while it is down for DB maintenance
> Disable chat e2e tests in staging while we do database maintenance

- tests/content-block-manager.spec.js
We’ve now replatformed Content Block Manager to be its own app. This updates the tests to use the new URL. I’ve also had to update the mainstreamPath variable to take account of the move to Postgres.
> (CM-482) Update tests to use Content Block Manager

- tests/assets.spec.js
- tests/frontend.spec.js
We changed the logic for previewing CSV attachments and the preview page is now served by /csv-preview route.
We also want to remove the /media route from government-frontend that redirects all requests made from gov.uk/media to assets.publishing.gov.uk/media.
> Replace /media path with /csv-preview for previewing CSV attachments

- tests/chat.spec.js
Chat in prod will be down for up to 2 hours while we do DB maintenance. Disable the e2e tests for it so we don't block other e2e tests passing.
> [DO NOT MERGE until maintenance] Disable chat e2e tests in production while DB maintenance is underwar

- tests/chat.spec.js
Reverts alphagov/govuk-e2e-tests#308
Once DB maintenance is complete and chat is back online, enable the e2e tests again in production
> Revert "Disable chat e2e tests in production while DB maintenance is underwar"

- tests/frontend.spec.js
Check `application.css` referenced in `frontend` loads OK
This test will help catch an issue where the application.css file uploaded, is not the same as the application.css file referenced in the HTML, which results in an unstyled page.
This is caused by a race condition which is a known issue - https://github.com/alphagov/govuk-infrastructure/issues/2447
> Check `application.css` referenced in `frontend` loads OK

- tests/collections.spec.js
- tests/feedback.spec.js
- tests/finder-frontend.spec.js
- tests/government-frontend.spec.js
- tests/smart-answers.spec.js
Check `application.css` file loads in frontend apps, with the exceptions of the apps below:
* **email-alert-frontend**: there is no test file in place for this application, we could add a similar check for a page that does not required you to be signed in, for example https://www.gov.uk/email/subscriptions/single-page/new?topic_id=keeping-a-pet-pig-or-micropig
* **static**: as static is manually deployed, there is no test file in place for static, and it seems very unlikely it will be impacted by the race condition issue as it is manually deployed
This test will help catch an issue where the application.css file uploaded, is not the same as the application.css file referenced in the HTML, which results in an unstyled page.
This is caused by a race condition which is a known issue - …
> Check application.css file loads in frontend apps
